### ISSUE TITLE
Internal PE-D

### ISSUE THREAD

**Issue by pyk595** [AY2122S2-CS2103T-T17-3/tp#186]
Simulate PE-D and report any findings here!

Best to follow a format like

```
## [<Docs/Bug/Flaw>-<specifics>-[additional detail]] <Descriptive one-liner of issue>

Severity: <High, Medium, Low, Very Low>

<Details such as steps to reproduce or screenshots>

[Suggestions]
```

<details>
<summary>Click here to view the examples</summary>

## [Docs-UG-Add] Invalid sample command for `add`. 

Severity: Very low

Sample command was missing one mandatory field. 

---

## [Bug-Find] Separator value does not work. 

Severity: Medium

Find command allows searching of values separated by commas, but the input does not seem to be separated. 

Steps to reproduce:
1. `find test, abc`
2. Returns an error message saying `unable to "test, abc"`. (can include screenshot)

Suggestion:
- Check if the user input that is parsed splits by commas, 
- otherwise update the UG and sample commands to indicate how values are separated.
</details>

Massive shout out to everyone who took part in this! ❤️

Thanks for helping us with this and all the best!!!

**Comment by yusufaine** [comment]
Testing!!

**Comment by pyk595** [comment]
# Example of reports:
## [Docs-UG-Add] Invalid sample command for add.
Severity: Very low

Sample command was missing one mandatory field.

---
## [Bug-Find] Separator value does not work.
Severity: Medium

Find command allows searching of values separated by commas, but the input does not seem to be separated.

Steps to reproduce:

`find test, abc`
Returns an error message saying `unable to "test, abc"`. (can include screenshot)
Suggestion:

- Check if the user input that is parsed splits by commas,
- otherwise update the UG and sample commands to indicate how values are separated.

**Comment by blaketingyu** [comment]
## [Docs] <Minor UG Issues for the first page>

Severity: <Very Low>

![image](https://user-images.githubusercontent.com/77196632/162360699-06f05765-0035-4029-9edc-407791df9a63.png)

Just minor suggestions! 

`Suggestions`
- Insurance Agents -> insurance agents
- to manage their client contacts -> manage their client contacts. 
- Activities -> Tasks? (My english is bad but just suggestions)
- Maybe can remove the "Using" in "using AIA can help you achieve the following"
- time sensitive -> time-sensitive
- tasks to do for each client -> to-do tasks for each client
- This user guide offers the following to insurance agents -> This user guide offers the following for insurance agents

**Comment by blaketingyu** [comment]
## [Docs-Screenshots-UG-not-clear] Screenshots for certain commands in the User Guide are pixelated and not as clear. 

Severity: Very Low

Some screenshots are pixelated and blurry as compared to the last few commands in the UG
![image](https://user-images.githubusercontent.com/77196632/162362072-7acb1c96-14ef-4513-ba04-06bf128eae6b.png)

Unclear Screenshots for `add`, `list`, `edit`, `find`, `tag`, `untag`, `tags`, `#`, `log`, `logs`, `unlog`, `within`, `after`. 

Suggestions:
The screenshots after the command `after`, starting from `remind` is really clear and of high definition so I believe you can keep your screenshots to that standard!

**Comment by blaketingyu** [comment]
## [Docs-UG-edit] Minor User Guide phrasing for edit command 

Severity: Very Low
![image](https://user-images.githubusercontent.com/77196632/162363640-675cb466-8a2e-4322-899a-492a433dfe47.png)

Suggestions:
"if you realize you need to update a client's outdated information or change a specific field"

**Comment by blaketingyu** [comment]
## [Docs-UG-Untag-Typo] Minor Typo

Severity: Very Low
Probably just a typo you guys missed. 
![image](https://user-images.githubusercontent.com/77196632/162363850-455d7c18-6d00-4e76-9380-2ec2a695c5c4.png)

Suggestions:
cateogory -> category

**Comment by blaketingyu** [comment]
## [Flaw] `Add` Command Email Regular Expression

Severity: Very Low

Added a new contact with email `sexgod@pornhub`. Was wondering whether the email check allows it without checking for 
".com" at the back. 

![image](https://user-images.githubusercontent.com/77196632/162364661-6656bf78-4404-4089-aed6-051893207715.png)


Suggestions:
If this is the supposed behavior, is it possible to include it in the user guide? I believe ab3's email check was not as strict and maybe you all are using the old implementation. Not really that big of an issue to me, just raising it up in case this is not the supposed behavior.

**Comment by blaketingyu** [comment]
## [Refactor issue] Super minor spacing issue for `edit` invalid command display

Severity: Ultra Low

![image](https://user-images.githubusercontent.com/77196632/162366337-f28c1d37-93e7-4a16-932c-cd6231caccad.png)

Suggestions
Just needs an extra spacing after full stop for Dates.

**Comment by Oddcorner** [comment]
## [Flaw] Incorrect error given when using large index
![image](https://user-images.githubusercontent.com/90017908/162483604-708d84d9-bc98-4b9a-804b-e577faf02fd1.png)

Technically a valid command format. The index given is a positive integer too. The error message should be consistent when using 100 or 100000000000. 

![image](https://user-images.githubusercontent.com/90017908/162484235-a32e9c57-d76b-45fb-8b36-3b835f4c6410.png)

**Comment by Oddcorner** [comment]
## [Docs-UG-Quick Start] Inconsistent terms for menu bar

Mentioned `application bar` in step 7. But GUI labeling mentions the term `menu bar`

![image](https://user-images.githubusercontent.com/90017908/162484464-493c3191-8942-4589-92ab-26226b6ba6af.png)

**Comment by Oddcorner** [comment]
## [Feature-Flaw] Logs can be made before person's birthday

This is nitpicking but this behaviour seems wrong in my opinion.

![image](https://user-images.githubusercontent.com/90017908/162485917-cc9e06a0-97df-455a-935f-368b44f258de.png)

**Comment by yusufaine** [comment]
## [Bug-UI] Edit resets the current (filtered) list to view all contacts instead of persisting the view.

Really quite minor issue.

Steps to reproduce:
1. Filter list to a singular result,
2. Edit the contact (I added a tag),
3. Contact gets updated successfully but (1) is undone as it shows the `list`

This MAY be a slight hinderance for some with a lot of contacts as you can imagine if they want to see the actual change being displayed on the PersonCard, they'd have to re-filter/scroll down

Severity: Very low

![image](https://user-images.githubusercontent.com/29030941/162557702-a7ad691a-bc1f-433f-b3c1-4d8f782d2c2f.png)

**Comment by yusufaine** [comment]
# [Bug-UI] Unclear invalid person index (inconsistent error message?)

Again, minor issue.

Entering an index < 1 shows this, which explains what a "valid" index is:
![image](https://user-images.githubusercontent.com/29030941/162557853-eb4de4f8-5740-463d-875c-a153061e4055.png)

But entering an index > number of contacts shows this:
![image](https://user-images.githubusercontent.com/29030941/162557884-fa4e9a8b-d41f-4c72-9e06-0fa357b0e544.png)

**Comment by yusufaine** [comment]
# [Flaw-Tag] Tag modification 
(more of a suggestion to improve UX than anything for future implementation in DG or something)

As mentioned in the UG:
![image](https://user-images.githubusercontent.com/29030941/162557951-e3be2643-1f48-4883-9f45-a272c60bac34.png)

This works fine, but as a user, if I use `tag`, `untag`, shouldn't it be implied that I want to add/remove the tag for that contact so specifying t/ might be a little troublesome? Similarly for UX, you can consider using comma (or any other symbol) separated value to allow (un)tagging of multiple tags at once.

Example:
`tag 7 this, is, a, test`

**Comment by yusufaine** [comment]
[Bug/Suggestion] Adding log/output should follow some sort of sequencing.

Not sure if an output like this should be valid where I interacted with the client before my first "interaction".
![image](https://user-images.githubusercontent.com/29030941/162558094-46013349-9c1b-4e0b-91e6-08cb63273983.png)

If this is allowed, wouldn't it make sense to list the interactions in chronological order such that the "Actual first interaction?" is before the "First interaction"?

Another suggestion to make the specification of date to be optional. If not specified, it assumes today's date, otherwise, it would use the provided date.

**Comment by yusufaine** [comment]
# [Nit-UG] Table of content includes portion before it and itself

![image](https://user-images.githubusercontent.com/29030941/162558376-77349f95-15e4-4093-abc9-91b0851f3f14.png)

I just think this one is a little weird since you would scroll to TOC so the portions prior need not be linked. Similarly there's no need to mention the TOC in itself 😆

**Comment by yusufaine** [comment]
# [Bug-UG] Quick start does not address common "mainstream OS" ways to run JAR

The quick start currently assumes that the user:
1. Knows how to install Java JDK 11,
2. Step 4 is how MacOS users can run the application, this _should_ work for Windows too

Suggestion:
1. Provide a link to an install guide for Windows/MacOS (assume that Linux people know this stuff -- not too mainstream anyway)
2. Specifically mention that for MacOS, run it thru terminal, but Windows should be able to run by double-click.

**Comment by yusufaine** [comment]
# [Flaw/Suggestion-`find`, `#`] Functional similarity of the 2 commands

As a user, I think `find` should be able to filter according to the tag or name instead of needing 2 separate commands for one or the other. 

Suggestion:
* Each person can be represented as a string-representation of what it can be searched by
* Example: John Doe can be represented as a string as john, doe, <tags>. The only thing you need to consider is how strict the matching should be.

**Comment by yusufaine** [comment]
# [Bug-UG] Return to TOC indented with image

![image](https://user-images.githubusercontent.com/29030941/162558876-2ad7d431-508f-4a29-9f73-34ddd5734826.png)


I believe it's supposed to be outside the indent, might be because of some line break issue.

**Comment by yusufaine** [comment]
[Bug-UG] Make command summary more user friendly by linking actions to their sections

When I test the application, I jump straight to the command summary and had to return to TOC and jump to the right action to get information of how something is formatted (date), which is really a big hassle since I would have to scroll all the way down again if I want to go back to the command summary.

Suggestion:
* Link "Action" to their specific sections to make it easier for users to find out more details about the command, 
* adding a jump back to command summary isnt too necessary since it's at the bottom of the page and users can just scroll down all the way.

**Comment by pyk595** [comment]
@yusufaine @blaketingyu @Oddcorner thanks for picking up all these bugs, all the best for the submission! (I'll be closing this too)
